W4/cookbook_app2/config/routes.rb
CookbookApp2::Application.routes.draw do

  root to: 'users#index'
  resources :users
  resources :sessions

  #root to: 'categories#index'

  resources :categories
  resources :recipes
  resources :ingredients

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'login' , to: 'sessions#create', as: 'new_session'

  match 'search', to: 'categories#search', via: [:get, :post], as: :search


end
  
  

  

W4/cookbook_app2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookbookApp2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
    <div class="flash-messagxe flash-message-<%= name %>">
      <%= msg %>
    </div>
  <% end %>

<% if current_user %>
    <p>hello <%= current_user.email %></p>
  <% end %>
<p>
    <%= link_to 'log me out!', logout_path %>
  </p>
<h1 style="color: red">Cookbook App 2</h1>
<nav>
<ul>
<li style="color: blue"><%= link_to 'Categories', categories_path, class:"category" %></li>
<li style="color: blue"><%= link_to 'Recipes', recipes_path, class:"me" %></li>
<li style="color: blue"><%= link_to 'New recipe',new_recipe_path, class:"jo" %></li>
<li style="color: blue"><%= link_to 'Ingredients',ingredients_path, class:"l" %></li>
<li style="color: blue"><%= link_to 'New ingredient',new_ingredient_path, class:"m" %></li>
</ul>
</nav>



<%= yield %>

</body>
</html>