W4/cookbook_habtm/config/routes.rb
CookbookOnRails::Application.routes.draw do
  resources :categories

  resources :ingredients

  resources :recipes

  root :to => 'recipes#index'
end

W4/cookbook_habtm/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :recipes
end

W4/cookbook_habtm/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, :image, :recipe_ids

  validates :name, presence: true

  has_many :ingredients_recipes
  
  has_many :recipes, through: :ingredients_recipes
end

W4/cookbook_habtm/app/models/ingredients_recipe.rb
class IngredientsRecipe < ActiveRecord::Base

belongs_to :ingredient
belongs_to :recipe


end

W4/cookbook_habtm/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name, :instructions, :category_id, :description, :ingredient_ids

  belongs_to :category

  validates :name, presence: true

  has_many :ingredients_recipes

  has_many :ingredients, through: :ingredients_recipes


end

W4/cookbook_habtm/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

W4/cookbook_habtm/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to @category, :notice => "Successfully created category."
    else
      render :action => 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to @category, :notice  => "Successfully updated category."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_url, :notice => "Successfully destroyed category."
  end
end

W4/cookbook_habtm/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(params[:ingredient])
    if @ingredient.save
      redirect_to @ingredient, :notice => "Successfully created ingredient."
    else
      render :action => 'new'
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update_attributes(params[:ingredient])
      redirect_to @ingredient, :notice  => "Successfully updated ingredient."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    redirect_to ingredients_url, :notice => "Successfully destroyed ingredient."
  end
end

W4/cookbook_habtm/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(params[:recipe])
    if @recipe.save
      redirect_to @recipe, :notice => "Successfully created recipe."
    else
      render :action => 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(params[:recipe])
      redirect_to @recipe, :notice  => "Successfully updated recipe."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_url, :notice => "Successfully destroyed recipe."
  end
end

W4/cookbook_habtm/app/helpers/application_helper.rb
module ApplicationHelper
end

W4/cookbook_habtm/app/helpers/categories_helper.rb
module CategoriesHelper
end

W4/cookbook_habtm/app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

W4/cookbook_habtm/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

W4/cookbook_habtm/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

W4/cookbook_habtm/app/helpers/recipes_helper.rb
module RecipesHelper
end

W4/cookbook_habtm/app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

W4/cookbook_habtm/app/views/categories/edit.html.erb
<% title "Edit Category" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @category %> |
  <%= link_to "View All", categories_path %>
</p>

W4/cookbook_habtm/app/views/categories/index.html.erb
<% title "Categories" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for category in @categories %>
    <tr>
      <td><%= category.name %></td>
      <td><%= link_to "Show", category %></td>
      <td><%= link_to "Edit", edit_category_path(category) %></td>
      <td><%= link_to "Destroy", category, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Category", new_category_path %></p>

W4/cookbook_habtm/app/views/categories/new.html.erb
<% title "New Category" %>

<%= render 'form' %>

<p><%= link_to "Back to List", categories_path %></p>

W4/cookbook_habtm/app/views/categories/show.html.erb
<% title "Category" %>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <%= link_to "Edit", edit_category_path(@category) %> |
  <%= link_to "Destroy", @category, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", categories_path %>
</p>

W4/cookbook_habtm/app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :instructions %><br />
    <%= f.text_area :instructions %>
  </p>
  <p>
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>

  <p>
    <%= hidden_field_tag 'recipe[ingredient_ids][]'%>
     <% Ingredient.all.each do |ingredient| %>
       <%= check_box_tag "recipe[ingredient_ids][]", ingredient.id, @recipe.ingredients.include?(ingredient), id: "recipe_ingredient_ids_#{ingredient.id}" %>
       <%= f.label :ingredient_ids, ingredient.name, for: "recipe_ingredient_ids_#{ingredient.id}" %>
       <br>
     <% end %>
  </p>


  <p><%= f.submit %></p>
<% end %>

W4/cookbook_habtm/app/views/recipes/edit.html.erb
<% title "Edit Recipe" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @recipe %> |
  <%= link_to "View All", recipes_path %>
</p>

W4/cookbook_habtm/app/views/recipes/index.html.erb
<% title "Recipes" %>

<table>
  <tr>
    <th>Name</th>
    <th>Instructions</th>
    <th>Category</th>
    <th>Description</th>
  </tr>
  <% for recipe in @recipes %>
    <tr>
      <td><%= recipe.name %></td>
      <td><%= recipe.instructions %></td>
      <td><%= recipe.category.try(:name) %></td>
      <td><%= recipe.description %></td>
      <td><%= link_to "Show", recipe %></td>
      <td><%= link_to "Edit", edit_recipe_path(recipe) %></td>
      <td><%= link_to "Destroy", recipe, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Recipe", new_recipe_path %></p>

W4/cookbook_habtm/app/views/recipes/new.html.erb
<% title "New Recipe" %>

<%= render 'form' %>

<p><%= link_to "Back to List", recipes_path %></p>

W4/cookbook_habtm/app/views/recipes/show.html.erb
<% title "Recipe" %>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>
<p>
  <strong>Instructions:</strong>
  <%= @recipe.instructions %>
</p>
<p>
  <strong>Category:</strong>
  <%= @recipe.category.try(:name) %>
</p>
<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>
<p>
  <strong>Ingredients:</strong><br>
  <% @recipe.ingredients.each do |ingredient| %>
    <%= ingredient.name %><br>
  <% end %>
</p>

<p>
  <%= link_to "Edit", edit_recipe_path(@recipe) %> |
  <%= link_to "Destroy", @recipe, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", recipes_path %>
</p>