W7/sass/sass_country_facts_app/config/routes.rb
CountryFactsApp::Application.routes.draw do
  
  root to: 'Continents#index'

  resources :countries
  resources :continents

  

end

W7/sass/sass_country_facts_app/app/models/continent.rb
class Continent < ActiveRecord::Base
  attr_accessible :hemisphere, :name

  has_many :countries, dependent: :destroy
  
end

W7/sass/sass_country_facts_app/app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :flag, :map, :name, :population, :summary, :video, :continent_id

  belongs_to :continent
end

W7/sass/sass_country_facts_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def load_continents
     @continents = Continent.all
  end
  
end

W7/sass/sass_country_facts_app/app/controllers/continents_controller.rb
class ContinentsController < ApplicationController
  before_filter :load_continents, except: [:update, :create, :delete]
  def index
    @continents = Continent.all
  end

  def new
    @continent = Continent.new
  end

  def create
    Continent.create params[:continent]
    redirect_to countries_path
  end

  def show
    @continent = Continent.find params[:id] 

  end

  def edit
    @continent = Continent.find params[:id]
  end

  def update
    @continent = Continent.find params[:id]
    @continent.update_attributes params[:continent]
    redirect_to @continent
  end

  def destroy
    @continent = Continent.find params[:id]
    @continent.destroy
    redirect_to countries_path
  end

end

W7/sass/sass_country_facts_app/app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_filter :load_continents, except: [:update, :create, :delete]
  def index
    @countries = Country.all
  end

  def new
    @country = Country.new
  end

  def create
    Country.create params[:country]
    redirect_to countries_path
  end

  def show
    @country = Country.find params[:id] 

  end

  def edit
    @country = Country.find params[:id]
  end

  def update
    @country = Country.find params[:id]
    @country.update_attributes params[:country]
    redirect_to @country
  end

  def destroy
    @country = Country.find params[:id]
    @country.destroy
    redirect_to countries_path
  end

end

W7/sass/sass_country_facts_app/app/helpers/application_helper.rb
module ApplicationHelper
end

W7/sass/sass_country_facts_app/app/helpers/continent_helper.rb
module ContinentHelper
end

W7/sass/sass_country_facts_app/app/views/application/_displaycountries.html.haml
.country
  - if @country.video == '' || @country.video == nil
    .poster
      %img{:src => @country.flag}
        %h1= link_to "#{@country.name}", country_path(@country)
  - else
    = video_tag @country.video,  controls: false, muted: true, type: 'video/webm'
    %h1= link_to "#{@country.name}", country_path(@country)
  .summary
    %p
      %img.map{:src => @country.map}
        %h2= country.name
        = @country.summary
        %span.population
          The current population of #{@country.name} is #{number_to_human(@country.population)}.

W7/sass/sass_country_facts_app/app/views/countries/_displaycountries.haml
.country
  - if @country.video == '' || @country.video == nil
    .poster
      %img{:src => @country.flag}
  - else
    = video_tag "assets/images/#{@country.video}",  controls: false, muted: true, type: 'video/webm'
  .summary
    %p
      %img.map{:src => @country.map}
        %h2= @country.name
        = @country.summary
        %span.population
          The current population of #{@country.name} is #{number_to_human(@country.population)}.
        %span.edit
          = link_to "Edit #{@country.name} ", edit_country_path

W7/sass/sass_country_facts_app/app/views/countries/_form.html.haml
= form_for(@country) do |c|
  .field
    = c.label :name
    = c.text_field :name
  .field
    = c.label :name
    = c.collection_select :continent_id, Continent.all, :id, :name
  .field
    = c.label :flag
    = c.text_field :flag
  .field
    = c.label :map
    = c.text_field :map
  .field
    = c.label :video
    = c.text_field :video
  .field
    = c.label :population
    = c.text_field :population
  .field
    = c.label :summary
    = c.text_field :summary
  .actions
    = c.submit

W7/sass/sass_country_facts_app/app/views/countries/edit.html.haml
.new
  %h1 Edit Country
  = render 'form'

W7/sass/sass_country_facts_app/app/views/countries/index.html.haml
.country
  = render 'displaycountries'

W7/sass/sass_country_facts_app/app/views/countries/new.html.haml
.new
  %h1 New Country
  = render 'form'

W7/sass/sass_country_facts_app/app/views/countries/show.html.haml
.country
  = render 'displaycountries'